name: Install

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  Windows:
    runs-on: windows-11-arm
    steps:
      - name: Test Arch
        run: |
          Write-Host "host arch env: $env:PROCESSOR_ARCHITECTURE"
          echo "import platform`nprint(platform.machine())" > a.py
          python a.py
