name: Install

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  Windows:
    runs-on: windows-11-arm
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Test Arch
        run: |
          vcpkg --version
          Write-Host "host arch env: $env:PROCESSOR_ARCHITECTURE"
          python --version
          python -c "import platform; print(platform.machine())"
