name: Wine Tests
on:
  push:

jobs:
  ubuntu:
    runs-on: ubuntu-24.04-arm
    container: ghcr.io/mstorsjo/wine
    steps:
      - name: Install prerequisites
        run: |
          sudo apt-get update && sudo apt-get install python3 msitools ca-certificates cmake ninja-build winbind meson
          WINE=$(command -v wine64 || command -v wine || false)
          curl -s -L -O https://github.com/wine-mono/wine-mono/releases/download/wine-mono-10.4.1/wine-mono-10.4.1-x86.msi
          $WINE msiexec /i wine-mono-10.4.1-x86.msi
          ls ${WINEPREFIX:-$HOME/.wine}/drive_c/windows/mono